const { Router } = require('express');
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const systemLogRoutes = require('./systemLog.routes');
const storageRoutes = require('./storage.routes');
const mapProxyRoutes = require('./map-proxy.routes');
const layerRoutes = require('./layer.routes');
const webMapRoutes = require('./web-map.routes');
const cmsRoutes = require('./cms.routes');
const remoteSensingRoutes = require('./remote-sensing.routes');
const spatialStatisticsRoutes = require('./spatial-statistics.routes');
const fieldReportRoutes = require('./field-report.routes');
const mobileGisRoutes = require('./mobile-gis.routes');
const apiRegistryRoutes = require('./api-registry.routes');
const sharedLayerRoutes = require('./shared-layer.routes');
const kttvRoutes = require('./kttv.routes');

const router = Router();

router.use('/auth', authRoutes);
router.use('/admin/users', userRoutes.adminRouter);
router.use('/admin/system-logs', systemLogRoutes.adminRouter);
router.use('/storage', storageRoutes);
router.use('/maps', mapProxyRoutes);
router.use('/admin/layers', layerRoutes);
router.use('/web-map', webMapRoutes);
router.use('/cms', cmsRoutes.publicRouter);
router.use('/admin/cms', cmsRoutes.adminRouter);
router.use('/remote-sensing', remoteSensingRoutes.publicRouter);
router.use('/admin/remote-sensing', remoteSensingRoutes.adminRouter);
router.use('/statistics', spatialStatisticsRoutes.publicRouter);
router.use('/admin/statistics', spatialStatisticsRoutes.adminRouter);
router.use('/field-reports', fieldReportRoutes.publicRouter);
router.use('/admin/field-reports', fieldReportRoutes.adminRouter);
router.use('/devices', fieldReportRoutes.deviceRouter);
router.use('/mobile', mobileGisRoutes);
router.use('/admin/api-registry', apiRegistryRoutes);
router.use('/shared', sharedLayerRoutes);
router.use('/admin/kttv', kttvRoutes.adminRouter);

module.exports = router;
