'use strict';
if(process.env.DB_NAME!=='campha_test'){throw new Error('Sprint 6a integration chỉ chạy trên campha_test');}
const db=require('../../../configs/database');const repository=require('../../../repositories/remote-sensing.repository');
const PREFIX='it_s6a_';let userId,files=[];
const cleanup=async()=>{await db.query(`DELETE FROM raster.satellite_images WHERE scene_code LIKE $1`,[`${PREFIX}%`]);await db.query(`DELETE FROM core.file_objects WHERE original_name LIKE $1`,[`${PREFIX}%`]);};
const input=(n,fileId,date,platform='sentinel-2',coverage='campha-core')=>({sceneCode:`${PREFIX}${n}`,title:`${PREFIX}Ảnh ${n}`,platform,thematicGroup:n===1?'water':'urban',coverageKey:coverage,acquiredAt:date,productLevel:'L2A',resolutionM:10,cloudCoverPercent:n*5,orbitNumber:10+n,description:'fixture',fileObjectId:fileId});
describe('Sprint 6a satellite PostgreSQL integration',()=>{
 beforeAll(async()=>{await cleanup();const {rows:[u]}=await db.query(`SELECT id FROM auth.users WHERE deleted_at IS NULL ORDER BY id LIMIT 1`);userId=u.id;const values=[];const params=[];for(let i=1;i<=4;i++){const ext=i===4?'pdf':'tif';params.push(`raster/${PREFIX}${i}.${ext}`,userId,`${PREFIX}${i}.${ext}`,i===4?'application/pdf':'image/tiff');const o=(i-1)*4;values.push(`('raster','campha-raster',$${o+1},$${o+2},$${o+3},$${o+4},'clean','ready',NOW())`);}const {rows}=await db.query(`INSERT INTO core.file_objects(category,bucket,object_key,owner_user_id,original_name,detected_mime,scan_status,lifecycle_status,ready_at) VALUES ${values.join(',')} RETURNING *`,params);files=rows;});
 afterAll(async()=>{await cleanup();db.stopPoolMonitor();await db.pool.end();});
 test('creates ready owned GeoTIFF and rejects wrong type',async()=>{const created=await repository.create(input(1,files[0].id,'2024-01-01'),userId);expect(created).not.toBeNull();await expect(repository.create(input(4,files[3].id,'2024-02-01'),userId)).resolves.toBeNull();});
 test('filters pages and sorts acquisition time',async()=>{await repository.create(input(2,files[1].id,'2025-01-01','landsat-8'),userId);await repository.create(input(3,files[2].id,'2026-01-01'),userId);const result=await repository.list({q:PREFIX,platform:'sentinel-2',page:1,limit:10,sort:'acquiredAt:asc'});expect(result.items.map(x=>x.scene_code)).toEqual([`${PREFIX}1`,`${PREFIX}3`]);expect(result.items.every(x=>x.object_key===undefined)).toBe(true);});
 test('categorize and delete reject stale optimistic versions',async()=>{const row=(await repository.list({q:`${PREFIX}3`,page:1,limit:10,sort:'acquiredAt:desc'})).items[0];const changed=await repository.categorize(row.id,'forest',row.updated_at,userId);expect(changed.thematic_group).toBe('forest');await expect(repository.categorize(row.id,'water',row.updated_at,userId)).resolves.toBeNull();await expect(repository.remove(row.id,row.updated_at)).resolves.toBeNull();await expect(repository.remove(row.id,changed.updated_at)).resolves.toMatchObject({id:String(row.id)});});
});