'use strict';
if(process.env.DB_NAME!=='campha_test'){throw new Error('Sprint 6a HTTP integration chỉ chạy trên campha_test');}
jest.mock('../../../middlewares/auth.middleware',()=>{const {Api401Error}=require('../../../core/error.response');const user=req=>{const role=req.get('x-test-role');if(!role){return null;}const manager=role!=='citizen';return{id:Number(req.get('x-test-user-id')),role,org_id:1,role_permissions:{raster:manager?{read:true,create:true,delete:true,categorize:true,search:true,compare:true,download:true}:{search:true,compare:true,download:true}}};};return{optionalAuth:(req,_res,next)=>{req.user=user(req);next();},verifyToken:(req,_res,next)=>{req.user=user(req);next(req.user?undefined:new Api401Error('Login required'));},enforcePasswordChange:(_req,_res,next)=>next(),requireRole:()=>()=>{},requirePermission:()=>()=>{},hasPermission:()=>true};});
jest.mock('../../../services/minio.service',()=>({...jest.requireActual('../../../services/minio.service'),getPresignedDownloadUrl:jest.fn().mockResolvedValue({url:'https://signed.invalid/raster',expiresAt:new Date('2026-01-01')})}));
const request=require('supertest');const app=require('../../../app');const db=require('../../../configs/database');const repository=require('../../../repositories/remote-sensing.repository');
const PREFIX='it_s6a_http_';let userId,before,after,fileIds=[];const auth=(req,role='citizen')=>req.set('x-test-role',role).set('x-test-user-id',String(userId));const cleanup=async()=>{await db.query(`DELETE FROM raster.satellite_images WHERE scene_code LIKE $1`,[`${PREFIX}%`]);await db.query(`DELETE FROM core.file_objects WHERE original_name LIKE $1`,[`${PREFIX}%`]);};
describe('Sprint 6a remote sensing HTTP integration',()=>{
 beforeAll(async()=>{await cleanup();const {rows:[u]}=await db.query(`SELECT id FROM auth.users WHERE deleted_at IS NULL ORDER BY id LIMIT 1`);userId=u.id;const {rows}=await db.query(`INSERT INTO core.file_objects(category,bucket,object_key,owner_user_id,original_name,detected_mime,scan_status,lifecycle_status,ready_at) VALUES ('raster','campha-raster',$1,$2,$3,'image/tiff','clean','ready',NOW()),('raster','campha-raster',$4,$2,$5,'image/tiff','clean','ready',NOW()) RETURNING id`,[`raster/${PREFIX}1.tif`,userId,`${PREFIX}1.tif`,`raster/${PREFIX}2.tif`,`${PREFIX}2.tif`]);fileIds=rows.map(x=>x.id);before=await repository.create({sceneCode:`${PREFIX}1`,title:`${PREFIX}before`,platform:'sentinel-2',coverageKey:'campha-http',acquiredAt:'2024-01-01',fileObjectId:fileIds[0]},userId);after=await repository.create({sceneCode:`${PREFIX}2`,title:`${PREFIX}after`,platform:'sentinel-2',coverageKey:'campha-http',acquiredAt:'2025-01-01',fileObjectId:fileIds[1]},userId);});
 afterAll(async()=>{await cleanup();db.stopPoolMonitor();await db.pool.end();});
 test('anonymous searches and compares without object paths',async()=>{const list=await request(app).get(`/api/v1/remote-sensing/images?q=${PREFIX}`).expect(200);expect(list.body.data.items).toHaveLength(2);expect(JSON.stringify(list.body)).not.toContain('object_key');const compare=await request(app).get(`/api/v1/remote-sensing/compare?beforeId=${before.id}&afterId=${after.id}`).expect(200);expect(compare.body.data.before.url).toContain('signed.invalid');expect(JSON.stringify(compare.body)).not.toContain('object_key');});
 test('download requires login while citizen is allowed',async()=>{await request(app).get(`/api/v1/remote-sensing/images/${before.id}/download-url`).expect(401);await auth(request(app).get(`/api/v1/remote-sensing/images/${before.id}/download-url`)).expect(200);});
 test('citizen cannot create while manager can categorize',async()=>{await auth(request(app).post('/api/v1/admin/remote-sensing/images')).send({sceneCode:`${PREFIX}blocked`,title:'Blocked',platform:'sentinel-2',coverageKey:'campha-http',acquiredAt:'2026-01-01',fileObjectId:fileIds[0]}).expect(403);const detail=await request(app).get(`/api/v1/remote-sensing/images/${before.id}`).expect(200);await auth(request(app).patch(`/api/v1/admin/remote-sensing/images/${before.id}/category`),'so_tnmt').send({thematicGroup:'forest',expectedUpdatedAt:detail.body.data.updated_at}).expect(200);});
});